#!/usr/bin/env bash
# Installs the packages the shell and its configs rely on (CachyOS only,
# via pacman — skip with --no-packages), then symlinks this repo's
# dotfiles/ into place under $XDG_CONFIG_HOME. Existing real files/dirs at
# the target are backed up (never deleted). --yes skips the confirmation.
set -euo pipefail

NO_PACKAGES=0
ASSUME_YES=0
for arg in "$@"; do
  case "$arg" in
  --no-packages) NO_PACKAGES=1 ;;
  --yes | -y) ASSUME_YES=1 ;;
  *)
    echo "usage: $0 [--no-packages] [--yes]" >&2
    exit 2
    ;;
  esac
done

# The package list and names are CachyOS's (Arch plus its own repos).
OS_ID="$(. /etc/os-release 2>/dev/null && echo "${ID:-}")"
if [ "$OS_ID" != "cachyos" ]; then
  echo "This install script only supports CachyOS (found: ${OS_ID:-unknown})." >&2
  exit 1
fi

cat <<'EOF'
muthur-shell replaces your desktop configuration.

  Back up your dotfiles before going on. Existing configs for bash,
  starship, fuzzel, quickshell, labwc, Hyprland, niri, alacritty, herdr,
  Neovim, yazi and btop are moved aside to *.bak.<date> and replaced by
  symlinks into this repo, and once running the shell rewrites generated
  files on every theme switch (GTK's gtk.css, Firefox's userChrome.css
  import and user.js pref, the color-scheme and GTK theme settings).

EOF
if [ "$ASSUME_YES" -ne 1 ]; then
  read -r -p "Continue? [y/N] " answer
  case "$answer" in
  [yY] | [yY][eE][sS]) ;;
  *)
    echo "Aborted."
    exit 1
    ;;
  esac
  echo
fi

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$REPO_DIR/dotfiles"
CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

# Everything the configs invoke or the panels talk to. herdr (the terminal
# workspace manager config in dotfiles/herdr) isn't packaged and is
# installed separately.
PACKAGES=(
  labwc          # compositor (dotfiles/labwc)
  hyprland       # the other supported compositors (dotfiles/hypr, dotfiles/niri)
  niri
  quickshell     # the shell itself
  fuzzel         # launcher ([>_], Super+Space)
  alacritty      # terminal (themed; Super+Return and the labwc menu)
  starship       # prompt (dotfiles/starship, themed via ANSI colors)
  yazi           # file manager (dotfiles/yazi, themed via ANSI colors; Super+E)
  btop           # system monitor (dotfiles/btop + the generated theme)
  swaybg         # wallpaper (labwc autostart)
  kanshi         # output profiles (labwc autostart)
  wdisplays      # output layout GUI ([SYS] > DISPLAY > ARRANGE)
  mako           # notifications (labwc autostart)
  swayidle       # idle timer (labwc autostart)
  swaylock       # locker: idle lock and the drawer's LOCK button
  wlopm          # screen power on idle (labwc autostart)
  neovim         # dotfiles/nvim (LazyVim) + the generated colorscheme
  noto-fonts     # Noto Sans Mono, the shell's face
  networkmanager # [SYS] > NETWORK
  bluez          # [SYS] > BT
  bluez-utils    # bluetoothctl, used by the BT tab
  pipewire       # [SYS] > AUDIO
  wireplumber
  upower # [POW]
  polkit # lets systemctl suspend/poweroff run without root
  xdg-desktop-portal-gtk # serves the light/dark color-scheme to apps
)

install_packages() {
  echo "Installing packages (sudo pacman -S --needed)..."
  sudo pacman -S --needed "${PACKAGES[@]}"
  echo
}

if [ "$NO_PACKAGES" -ne 1 ]; then
  install_packages
fi

# "source relative to dotfiles/" -> "target relative to \$CONFIG_HOME",
# or to \$HOME when the target starts with "~/".
LINKS=(
  "bash/bashrc:~/.bashrc"
  "starship/starship.toml:starship.toml"
  "fuzzel:fuzzel"
  "quickshell/muthur:quickshell/muthur"
  "labwc:labwc"
  "hypr:hypr"
  "niri:niri"
  "alacritty:alacritty"
  "herdr/config.toml:herdr/config.toml"
  "nvim:nvim"
  "yazi:yazi"
  "btop:btop"
)

link_one() {
  local src="$DOTFILES_DIR/$1"
  local dest
  case "$2" in
  "~/"*) dest="$HOME/${2#\~/}" ;;
  *) dest="$CONFIG_HOME/$2" ;;
  esac

  if [ ! -e "$src" ]; then
    echo "skip: source missing: $src" >&2
    return
  fi

  mkdir -p "$(dirname "$dest")"

  if [ -L "$dest" ]; then
    if [ "$(readlink -f "$dest")" = "$(readlink -f "$src")" ]; then
      echo "ok:      $dest already linked"
      return
    fi
    echo "replacing stale symlink: $dest"
    rm "$dest"
  elif [ -e "$dest" ]; then
    local backup
    backup="${dest}.bak.$(date +%Y%m%d%H%M%S)"
    echo "backing up existing $dest -> $backup"
    mv "$dest" "$backup"
  fi

  ln -s "$src" "$dest"
  echo "linked:  $dest -> $src"
}

for pair in "${LINKS[@]}"; do
  link_one "${pair%%:*}" "${pair#*:}"
done

# The shell writes GTK's user gtk.css on every theme switch; keep a copy of
# one it didn't write itself before that happens.
for gtk_css in "$CONFIG_HOME/gtk-3.0/gtk.css" "$CONFIG_HOME/gtk-4.0/gtk.css"; do
  if [ -f "$gtk_css" ] && ! grep -q "Generated by ThemeStore.qml" "$gtk_css"; then
    backup="${gtk_css}.bak.$(date +%Y%m%d%H%M%S)"
    echo "backing up existing $gtk_css -> $backup"
    mv "$gtk_css" "$backup"
  fi
done

# niri's config include()s the generated colors.kdl and refuses to load
# when it's missing, so seed a grey one for the first start; the shell
# overwrites it with the preset's colors as soon as it runs.
NIRI_COLORS="$DOTFILES_DIR/niri/colors.kdl"
if [ ! -e "$NIRI_COLORS" ]; then
  cat >"$NIRI_COLORS" <<'KDL'
// Placeholder until ThemeStore.qml generates this file; do not edit.
layout {
    border {
        active-color "#aaaaaa"
        inactive-color "#555555"
        urgent-color "#ffffff"
    }
}
KDL
  echo "seeded:  $NIRI_COLORS (grey fallback until the shell runs)"
fi

# Make "open folder" from other apps land in yazi rather than a GUI one.
if command -v xdg-mime >/dev/null && [ -f /usr/share/applications/yazi.desktop ]; then
  xdg-mime default yazi.desktop inode/directory
  echo "default: inode/directory -> yazi.desktop"
fi

echo
echo "Done. Launch the shell with: quickshell -c muthur"
