-- Tells LazyVim to use the "muthur" colorscheme, which lives at
-- colors/muthur.lua (generated by ThemeStore.qml, gitignored — see
-- .gitignore and the "nvim/colors/muthur.lua" install.sh link). No
-- plugin needed: LazyVim just runs `:colorscheme muthur`, and Neovim
-- finds it on runtimepath like any local colorscheme file. The watcher
-- in lua/config/autocmds.lua re-runs it when the file is regenerated.
return {
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "muthur",
    },
  },
}
